import cv2
img = cv2.imread("solar-system.jpg")
cv2.putText(img,
            "Sun",
            (130,100),
            cv2.FONT_HERSHEY_COMPLEX,
            2.0,
            (0,0,255)
            )
cv2.putText(img,
            "Mercury",
            (110,180),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (255,255,255)
            )
cv2.putText(img,
            "Venus",
            (190,260),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Earth",
            (290,260),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Mars",
            (390,260),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Jupiter",
            (490,100),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Saturn",
            (750,110),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Uranus",
            (960,118),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.putText(img,
            "Neptune",
            (1100,120),
            cv2.FONT_HERSHEY_COMPLEX,
            0.5,
            (0,255,0)
            )
cv2.imshow("output",img)
cv2.imwrite("Solar_systemwithname.jpg",img)
cv2.waitKey(0)
